### ISSUE TITLE
Cannot convert hex value to decimal on Mac

### ISSUE THREAD

**Issue by energee** [alexaubry/HexIt#1]
Uncaught TypeError: Cannot read property 'split' of undefined

1. Select hex value (Example 0x39F)
2. Try to convert with Shift + Control + D3. Error below is produced..

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [HexIt](https://github.com/alexaubry/HexIt) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/tslesinski/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:823

TypeError: Cannot read property 'split' of undefined
    at Selection.module.exports.Selection.insertText (/app.asar/src/selection.js:462:28)
    at /app.asar/src/text-editor.js:1117:29
    at /app.asar/src/text-editor.js:1156:28
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:818:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1589:26)
    at /app.asar/src/text-editor.js:1150:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2563:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2529:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1148:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1114:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at Object.toDecimal (/packages/HexIt/lib/hex-it.js:48:20)
    at /packages/HexIt/lib/hex-it.js:18:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -5:01.0 hex-it:decimal (input.hidden-input)
  2x -3:50.7.0 editor:duplicate-lines (input.hidden-input)
  2x -3:48 core:undo (input.hidden-input)
     -3:43 hex-it:decimal (input.hidden-input)
     -3:33.9.0 intentions:highlight (input.hidden-input)
     -3:29.8.0 core:undo (input.hidden-input)
     -3:27.2.0 editor:duplicate-lines (input.hidden-input)
     -3:25.9.0 core:undo (input.hidden-input)
  3x -3:22.6.0 hex-it:decimal (input.hidden-input)
     -1:51.8.0 editor:duplicate-lines (input.hidden-input)
     -1:50.4.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
color-picker 2.2.5 
command-logger 0.23.0 
drupal 1.9.0 
editor-stats 0.17.0 
fizzy 0.21.0 
git-blame 0.4.12 
git-plus 7.3.3 
HexIt 1.0.1 
intentions 1.1.2 
linter 2.1.2 
linter-twig 0.1.1 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
minimap 4.26.8 
monokai 0.22.0 
php-debug 0.2.4 
php-twig 4.0.0 
toggle-quotes 1.0.1 
Zen 0.16.4 
zentabs 0.8.8 
```

**Comment by alexaubry** [comment]
@energee Thanks for reporting! This crash has been fixed in the 1.0.2 release.
